Repository BHoM/Excel_UI, pull requests merged in 2019-11, with the labels that each got.

#163 Remove UpdateProperty formula
  Excel_UI/Excel_UI.csproj
  Excel_UI/UI/Components/Adapter/UpdateProperty.cs
Labels: type:compliance

#169 Align with changes of the SelectorMenu class name
  Excel_UI/UI/Templates/SelectorMenuUtil.cs
  Excel_UI/UI/Templates/SelectorMenu_RibbonXml.cs
Labels: type:external-api-changes

#170 Remove the ability to create typed objects from the CreateCustom component
  Excel_UI/UI/Callers/CreateCustom.cs
  Excel_UI/UI/Components/oM/CreateCustom.cs
Labels: type:compliance

#168 Add Engine Method to get filename
  Excel_Engine/Excel_Engine.csproj
  Excel_Engine/Query/GetFilename.cs
Labels: type:feature
