Repository BHoM/Excel_UI, pull requests merged in 2020-01, with the labels that each got.

#180 Bump AssemblyFileVersion to 3.1
  Excel_Engine/Properties/AssemblyInfo.cs
  Excel_UI/Properties/AssemblyInfo.cs
  Excel_oM/Properties/AssemblyInfo.cs
Labels: type:compliance

#172 Aligning with changes in BHoMAdapter Refactoring Level 04
  Excel_UI/Excel_UI.csproj
  Excel_UI/UI/Components/Adapter/Remove.cs
Labels: type:external-api-changes

#189 Add CI files and checks
  .ci/CloneTest.ps1
  .ci/check-all-depandants.yml
  .ci/check-core.yml
  .ci/check-installer.yml
  .ci/run-compliance-tests.yml
  .ci/testSettings.runsettings
  core.txt
  dependants.txt
  dependencies.txt
Labels: type:compliance

#190 Adding basic null check when a component request is received from global search
  Excel_UI/Addin/AddIn.cs
Labels: type:bug
