Repository BHoM/Excel_UI, pull requests merged in 2020-09, with the labels that each got.

#250 Reference office.dll from libs folder
  Excel_UI/Excel_UI.csproj
  libs/office.dll
Labels: type:compliance

#251 Fix multi-output formulas
  Excel_UI/Addin/AddIn_Formulas.cs
  Excel_UI/Caller/CallerFormula_Run.cs
  Excel_UI/Templates/FormulaDataAccessor.cs
Labels: type:bug

#255 Fix Explode failing when going deep finds nulls
  Excel_Engine/Query/Explode.cs
Labels: type:bug

#257 Fix additional parameters in formula name for method with IOutput output
  Excel_UI/Addin/AddIn_Formulas.cs
Labels: type:bug

#259 Change type representation in cell to a more explicit description
  Excel_UI/Addin/AddIn_Converts.cs
Labels: type:question
